app = "comic-scanner"
primary_region = "dfw"

[env]
  PORT = "8000"

[build]
  dockerfile = "./Dockerfile"

[processes]
app = "gunicorn -w 4 -b 0.0.0.0:8000 app:app"

[http_service]
  processes = ["app"]   # <-- This links the HTTP service to your app process
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 1

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
